Portfolio: Mobile Version
julie-ify/Portfolio-Mobile-version pull request #2
Opened 2021-07-08 18:49 UTC by julie-ify

## Portfolio: Work and About Section

In this project I: 
- Added work section to my portfolio
- Added about section to my portfolio
- Added style to sections
- Used CSS grid and flexbox to align my work properly
- Added section images to my portfolio

2021-07-08 19:22 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-08 19:22 UTC, arslanbisharat commented on index.html
> +          </div>
- [ ] The list of projects uses a ul tag to group them, and li per project

2021-07-08 19:22 UTC, arslanbisharat commented on index.html
> +            </div>
- [ ] The list of projects uses a ul tag to group them, and li per project

2021-07-08 19:22 UTC, arslanbisharat commented on index.html
> +              <button class="see-project-btn" type="button">See Project</button>
- [ ] The list of projects uses a ul tag to group them, and li per project

2021-07-08 19:22 UTC, arslanbisharat commented on index.html
> +          </div>
- [ ] The list of projects uses a ul tag to group them, and li per project

2021-07-08 19:22 UTC, arslanbisharat commented on index.html
> +            </div>
- [ ] The list of projects uses a ul tag to group them, and li per project

2021-07-08 19:22 UTC, arslanbisharat commented on index.html
> +        </div>
- [ ] The list of projects uses a ul tag to group them, and li per project

2021-07-08 19:25 UTC, arslanbisharat commented on styles.css
> +  color: #36b37e;
- [ ] You have used color property twice

2021-07-08 19:30 UTC, julie-ify commented on index.html
> +          </div>
Please do you mean the works?

2021-07-09 07:49 UTC, AshakaE approved these changes
### Hi @julie-ify , 

Your project is complete! 👏 ... it's time to merge it :shipit: 
Congratulations! 🎉 

### Optional suggestions
_Please tick checkboxes after making changes_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-07-09 07:50 UTC, julie-ify commented
Ok thanks

2021-07-09 07:54 UTC, merged